#!/bin/bash
#
# This file is licensed under the terms of the GNU General Public
# License version 2. This program is licensed "as is" without any
# warranty of any kind, whether express or implied.

. /etc/armbian-release
. /lib/init/vars.sh
. /lib/lsb/init-functions
. /usr/lib/armbian/armbian-common

NORFLASH=/mnt/norflash
INITED_NORFLASH=${NORFLASH}/.inited_jffs2
CONFIG_NORFLASH=${NORFLASH}/config
PYAIOT_BASE=/home/pi/.pyaiot
PYAIOT_CONFIG=${PYAIOT_BASE}/config

case "$1" in
	start)
	    # re-init jffs2 image
	    if [[ ! -f ${INITED_NORFLASH} ]]; then
	        umount ${NORFLASH}
	        flash_eraseall -j /dev/mtd0
	        mount ${NORFLASH}
	        touch ${INITED_NORFLASH}
	    fi

	    if [[ ! -d ${CONFIG_NORFLASH} ]]; then
	        rm -rf ${CONFIG_NORFLASH}
	        mkdir ${CONFIG_NORFLASH}
	        if [[ -f /etc/default/pyaiot-default-config ]]; then
	            cp /etc/default/pyaiot-default-config ${CONFIG_NORFLASH}/config.ini
	        else
	            touch ${CONFIG_NORFLASH}/config.ini
	        fi
	        chown -R pi.pi ${CONFIG_NORFLASH}
	    fi

        if [[ ! -d ${PYAIOT_BASE} ]]; then
            mkdir ${PYAIOT_BASE}
	        chown -R pi.pi ${PYAIOT_BASE}
        fi

        if [[ ! -h ${PYAIOT_CONFIG} ]]; then
            rm -rf ${PYAIOT_CONFIG}
            ln -s ${CONFIG_NORFLASH} ${PYAIOT_CONFIG}
        fi
		exit 0
		;;

	*)
		echo "Usage: $0 start"
		exit 0
	;;
esac